[[eudev]]
arch = "aarch64"
git-tree-sha1 = "446ddb48a50540d3e4d0898ee59ffffa8d032b6d"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "47495eb2aad6b96b5365cc109431ce7b05150f0e5dad37392fdcf748d88ea9dd"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.aarch64-linux-gnu.tar.gz"
[[eudev]]
arch = "aarch64"
git-tree-sha1 = "238f66d40451ef3ff3baedb5b388c1c8efd9f2ce"
libc = "musl"
os = "linux"

    [[eudev.download]]
    sha256 = "1339d77d64e4a7f3178dd527a0dbbaa98eea59b03d268c2439a0186c964a1576"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.aarch64-linux-musl.tar.gz"
[[eudev]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d555e97b5a4aedeb1c6222f0efd213a030f6f3bf"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "1b1a91ef8145d4d03822c145cc0af2383cb71795b803f33417278597e4c838ff"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.armv6l-linux-gnueabihf.tar.gz"
[[eudev]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "afdf84cdd3ae9ea150da4314a9a7bd125fbd5ef2"
libc = "musl"
os = "linux"

    [[eudev.download]]
    sha256 = "cc10cacee8eb1d606f29d3e138a62220d1d74ad88dadd146901d5f179451c39b"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.armv6l-linux-musleabihf.tar.gz"
[[eudev]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67ad73f0151b8bce5b0aef33de9b18fb0537d2b4"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "7b3a7889c46d6d3a865534d35e279fd8749749f362dfe7229aaca465796cede0"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.armv7l-linux-gnueabihf.tar.gz"
[[eudev]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "865d60ff55859836fa4fa26e4b59f1bdc129e535"
libc = "musl"
os = "linux"

    [[eudev.download]]
    sha256 = "2fe0f624d7770413a86ac2b6e02c308ac0d3ab1adba1882b4ff3246591f603f2"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.armv7l-linux-musleabihf.tar.gz"
[[eudev]]
arch = "i686"
git-tree-sha1 = "7405458111f677cb51bc2ab0a19e8df04dc3bdb4"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "5dfa9fe0243edd1798aabf603f4539dbd4b9b06155b3e0619338eb3cb0a0de96"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.i686-linux-gnu.tar.gz"
[[eudev]]
arch = "i686"
git-tree-sha1 = "26f647ea000c818f20ac842372c60768d9b16a20"
libc = "musl"
os = "linux"

    [[eudev.download]]
    sha256 = "a2e4deac997db866bc5228a5491ce455fab387feb9a58422f2b2dcd10e7ab376"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.i686-linux-musl.tar.gz"
[[eudev]]
arch = "powerpc64le"
git-tree-sha1 = "eecaffb5c87a27a9e15df8bc5466cbb12d37b285"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "f84492e9de055c6fb7d26b6b1eb5ea9dd41821cbbcd7bdd9985b8bafd579250e"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.powerpc64le-linux-gnu.tar.gz"
[[eudev]]
arch = "riscv64"
git-tree-sha1 = "b63badb7bf22f9c942cb4b1195bffbb1792692f8"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "cdd17e74424b3debdd542457a9dda69a1e98023b3a2a27f3914d72424351eedb"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.riscv64-linux-gnu.tar.gz"
[[eudev]]
arch = "x86_64"
git-tree-sha1 = "763be6a5ce77e0ca86d3e1b3a1c8ec499f8958f1"
libc = "glibc"
os = "linux"

    [[eudev.download]]
    sha256 = "3d9d7783b5d3f218924504de42aa1571de14619ebdb45b179ae956d2cbb168d9"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.x86_64-linux-gnu.tar.gz"
[[eudev]]
arch = "x86_64"
git-tree-sha1 = "5934ba4294b71a87b52ee4c22a5ab9fc1ac9d025"
libc = "musl"
os = "linux"

    [[eudev.download]]
    sha256 = "3757f8c6ba8a8c33f60cf8284528808c15341fa1ba971e8ee1a7519ccd0736ec"
    url = "https://github.com/JuliaBinaryWrappers/eudev_jll.jl/releases/download/eudev-v3.2.14+0/eudev.v3.2.14.x86_64-linux-musl.tar.gz"
